### ISSUE TITLE
Ottoman capital bug

### ISSUE THREAD

**Issue by Rodmuth2** [rileyo92/Rileyo-Divergence-Vic2-MP#1]
At the very start of the game, the ottoman empire may chose to go 3 directions, two of which will move the capital. If you pick the third direction, Europe, you will soon get an event anyway, moving your capital and in addition losing you prestige.

**Comment by rileyo92** [comment]
Adjusted event to now require you to either not to have your capital in Istanbul or Ankara or not own Edirne
