### ISSUE TITLE
Bug with Byzantium desicions

### ISSUE THREAD

**Issue by CaptainJ61** [rileyo92/Rileyo-Divergence-Vic2-MP#11]
When you form Byzantium you have a decision that lets you turn back into Greece for prestige, which brings back the decision to form Byz, so any player can loop between these two tags for infinite prestige. The AI will also do this automatically. Also added a save file with the issue.
[Greek_Empire1886_12_05.zip](https://github.com/rileyo92/Divergence-Expanded-MP/files/7004295/Greek_Empire1886_12_05.zip)

**Comment by rileyo92** [comment]
Added condition to Greece formation that you aren't Byzantium
