### ISSUE TITLE
Can't take over korea

### ISSUE THREAD

**Issue by sidetoside** [rileyo92/Rileyo-Divergence-Vic2-MP#14]
It's 1850 and i haven't got any event relating korea, or a decision to invade it. How are you supposed to take over korea?

**Comment by rileyo92** [comment]
Currently you need to manually invade it and eat it

**Comment by rileyo92** [comment]
It's to slow down Japan since they stand virtually unopposed in Asia

**Comment by rileyo92** [comment]
This is noted and might be addressed through a Japan rework but for now the issue will be closed
