### ISSUE TITLE
Rhine Confederation decision requirement broken

### ISSUE THREAD

**Issue by LoganGman** [rileyo92/Rileyo-Divergence-Vic2-MP#17]
![20220511002151_1](https://user-images.githubusercontent.com/63370392/167774872-7153a40d-ccf3-4c70-9431-6dfc272b3d7b.jpg)
![20220511002140_1](https://user-images.githubusercontent.com/63370392/167774892-81714b63-36c8-43ab-8d2c-548edbaa2d85.jpg)

says I need to sphere all of the "League of Munich" provinces yet I have done that and it does not work

**Comment by mys1** [comment]
Getting the same bug

**Comment by mys1** [comment]
So comparing the code for the Westfallen cores and the SGF cores this is the problem in decisions\Burgundy.txt

			WES = {
				all_core = {
					OR = {
						owned_by = THIS
						owner = {
							OR = {
								in_sphere = THIS
								vassal_of = THIS
							}
						}
						is_core = OLD
						is_core = LIP
					}
				}
			}

			SGF = {
				all_core = {
					OR = {
						owned_by = THIS
						owner = {
							in_sphere = THIS
							vassal_of = THIS
						}
						is_core = AUS
					}
				}
			}

WES works as expected. That you can own, sphere OR puppet (unless OLD/LIP core)

For SGF it's currently own OR sphere AND puppet (unless AUS core)

			SGF = {
				all_core = {
					OR = {
						owned_by = THIS
						owner = {
							OR = {
								in_sphere = THIS
								vassal_of = THIS
							}
						}
						is_core = AUS
					}
				}
			} 

Would fix it making it the same as WES.

**Comment by rileyo92** [comment]
I have made that change and thank you for bringing it up.
