### ISSUE TITLE
Ottoman empire arab decision bug

### ISSUE THREAD

**Issue by Rodmuth2** [rileyo92/Rileyo-Divergence-Vic2-MP#3]
When you play as the ottoman empire and click the decision "Restoring rule over arabia" you will get the cores, but the decision decision remains indefinitively afterwards and you can click it (to no benefit or harm) infinite times, and will have to disable it if you want the icon for "you have a decision that you can take" to not remain forever.

**Comment by rileyo92** [comment]
This has been fixed for next patch
