### ISSUE TITLE
Ottoman empire core bug.

### ISSUE THREAD

**Issue by Rodmuth2** [rileyo92/Rileyo-Divergence-Vic2-MP#4]
When you click the decision "restoring rule in arabia, you get cores on all arab land not previously covered by the Iraq and Egypt events, except for one, Ha'il, and also part of the province of Murzuk

**Comment by Rodmuth2** [comment]
The ottomans also get cores on Cyprus but not Crete, since both islands have significant turkish populations I presume it to be an oversight

**Comment by rileyo92** [comment]
Added starting Cores on Crete, Ha'il State removed
